[package]
name = "lapce-julia"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lapce-plugin = { git = "https://github.com/lapce/lapce-plugin-rust.git", rev = "48f0b0746c23fcd38a0c0aa37c7c85b15af4b4f0" }
